---
#cloud_controller_uri: api.vcap.me
service:
  name: mssql
  unique_id: b11411c8-1409-414c-848d-affd6ef3a604
  version: "2008 R2"
  description: 'Microsoft SQL Server Database'
  plans: ['free','expensive']
  default_plan: free
  tags: ['relational']
ip_route: localhost

index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/mssql_service.pid
node_timeout: 2
resque:
  host: localhost
  port: 5454
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}

plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      lifecycle:
        snapshot:
          quota: 5
        serialization: enable
        job: enable
    expensive:
      low_water: 1
      high_water: 20
