#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/uhurufs_gateway
LOG_DIR=/var/vcap/sys/log/uhurufs_gateway
PIDFILE=$RUN_DIR/uhurufs_gateway.pid

JOB_DIR=/var/vcap/jobs/uhurufs_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Uhurufs gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/uhurufs_gateway/services/uhurufs/bin/uhurufs_gateway \
         -c $JOB_DIR/config/uhurufs_gateway.yml \
         >>$LOG_DIR/uhurufs_gateway.stdout.log \
         2>>$LOG_DIR/uhurufs_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: uhurufs_gateway_ctl {start|stop}"

    ;;

esac
