#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/mssql_gateway
LOG_DIR=/var/vcap/sys/log/mssql_gateway
PIDFILE=$RUN_DIR/mssql_gateway.pid

JOB_DIR=/var/vcap/jobs/mssql_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "MsSQL gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/mssql_gateway/services/mssql/bin/mssql_gateway \
         -c $JOB_DIR/config/mssql_gateway.yml \
         >>$LOG_DIR/mssql_gateway.stdout.log \
         2>>$LOG_DIR/mssql_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: mssql_gateway_ctl {start|stop}"

    ;;

esac
